// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2kbV94TIDY9SUmQjS2HPXi71rkczHWs',
    appId: '1:322192606014:web:aa0d5917eef97233c8226f',
    messagingSenderId: '322192606014',
    projectId: 'medilink6928',
    authDomain: 'medilink6928.firebaseapp.com',
    storageBucket: 'medilink6928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6itr4kf9HrSfpOb-v4DaVAdBFkSDzhQ',
    appId: '1:322192606014:android:981f2239224a4fdac8226f',
    messagingSenderId: '322192606014',
    projectId: 'medilink6928',
    storageBucket: 'medilink6928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyTCcxD6L6AHOf4W5eOgnBpPerXFqdHI',
    appId: '1:322192606014:ios:14d8f4909dcf4862c8226f',
    messagingSenderId: '322192606014',
    projectId: 'medilink6928',
    storageBucket: 'medilink6928.appspot.com',
    iosBundleId: 'com.example.semesterprojectgetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpyTCcxD6L6AHOf4W5eOgnBpPerXFqdHI',
    appId: '1:322192606014:ios:14d8f4909dcf4862c8226f',
    messagingSenderId: '322192606014',
    projectId: 'medilink6928',
    storageBucket: 'medilink6928.appspot.com',
    iosBundleId: 'com.example.semesterprojectgetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2kbV94TIDY9SUmQjS2HPXi71rkczHWs',
    appId: '1:322192606014:web:242c184068ff35d6c8226f',
    messagingSenderId: '322192606014',
    projectId: 'medilink6928',
    authDomain: 'medilink6928.firebaseapp.com',
    storageBucket: 'medilink6928.appspot.com',
  );
}
